### PR TITLE
issue a warning in the .npmignore file

### PR DESCRIPTION
**Pull request by jamestalmage**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jamestalmage** [comment]
don't forget to publish to npm :smile:

**Comment by jonschlinkert** [comment]
I published 0.2.0 yesterday, make sure you bump the version :)

**Comment by jamestalmage** [comment]
ah,
I missed it at the bottom of the lint commit. sorry

**Comment by jonschlinkert** [comment]
lol no worries!

**Pull request merged**
